spring:
  profiles:
    active: dev

---
server:
  port: 3356
spring:
  profiles: dev
  application:
    name: microservicecloud-config-client

eureka:
  client:
    service-url:
      defaultZone: http://eureka8000.com:8000/eureka
---
server:
  port: 3357
spring:
  profiles: test
  application:
    name: microservicecloud-config-client

eureka:
  client:
    service-url:
      defaultZone: http://eureka9000.com:9000/eureka
